In [1]:
import os
import sys

Peu être utile

In [2]:
sys.path.append(os.path.abspath('../..'))

In [3]:
from src.preprocessing import load_and_clean_candidats_stats

In [4]:
df = load_and_clean_candidats_stats()
df.head()

,Code du département,Libellé du département,Code de la collectivité à statut particulier,Libellé de la collectivité à statut particulier,Code de la commune,Libellé de la commune,Nom de l'élu,Prénom de l'élu,Code sexe,Date de naissance,Code de la catégorie socio-professionnelle,Libellé de la catégorie socio-professionnelle,Date de début du mandat,Date de début de la fonction
0,01,Ain,NaN,NaN,01001,L'Abergement-Clémenciat,BOULON,Daniel,M,04/03/1951,74,Ancien cadre,18/05/2020,26/05/2020
1,01,Ain,NaN,NaN,01002,L'Abergement-De-Varey,ORSET,Max,M,02/11/1947,65,"Ouvrier qualifié de la manutention, du magasin...",18/05/2020,27/05/2020
2,01,Ain,NaN,NaN,01004,Ambérieu-En-Bugey,FABRE,Daniel,M,07/09/1961,74,Ancien cadre,18/05/2020,28/05/2020
3,01,Ain,NaN,NaN,01005,Ambérieux-En-Dombes,FORNES,Christine,F,06/07/1962,21,Artisan,02/05/2021,07/05/2021
4,01,Ain,NaN,NaN,01006,Ambléon,BIONDA,Annie,F,28/11/1951,77,Ancien employé,18/05/2020,25/05/2020

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34874 entries, 0 to 34873
Data columns (total 14 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Code du département                              34736 non-null  object
 1   Libellé du département                           34736 non-null  object
 2   Code de la collectivité à statut particulier     498 non-null    float64
 3   Libellé de la collectivité à statut particulier  498 non-null    object
 4   Code de la commune                               34874 non-null  object
 5   Libellé de la commune                            34874 non-null  object
 6   Nom de l'élu                                     34874 non-null  object
 7   Prénom de l'élu                                  34874 non-null  object
 8   Code sexe                                        34874 non-null  object
 9   Date de naissance                                34874 non-null  object
 10  Code de la catégorie socio-professionnelle       34874 non-null  int64
 11  Libellé de la catégorie socio-professionnelle    34874 non-null  object
 12  Date de début du mandat                          34874 non-null  object
 13  Date de début de la fonction                     34874 non-null  object
dtypes: float64(1), int64(1), object(12)
memory usage: 3.7+ MB

In [6]:
df['Nom Prenom'] = (
    df["Nom de l'élu"].astype(str) + " " + df["Prénom de l'élu"].astype(str)
)

In [7]:
df['Nom Prenom'].nunique()

34194

In [8]:



df.shape

(34874, 15)

In [9]:
df

,Code du département,Libellé du département,Code de la collectivité à statut particulier,Libellé de la collectivité à statut particulier,Code de la commune,Libellé de la commune,Nom de l'élu,Prénom de l'élu,Code sexe,Date de naissance,Code de la catégorie socio-professionnelle,Libellé de la catégorie socio-professionnelle,Date de début du mandat,Date de début de la fonction,Nom Prenom
0,01,Ain,NaN,NaN,01001,L'Abergement-Clémenciat,BOULON,Daniel,M,04/03/1951,74,Ancien cadre,18/05/2020,26/05/2020,BOULON Daniel
1,01,Ain,NaN,NaN,01002,L'Abergement-De-Varey,ORSET,Max,M,02/11/1947,65,"Ouvrier qualifié de la manutention, du magasin...",18/05/2020,27/05/2020,ORSET Max
2,01,Ain,NaN,NaN,01004,Ambérieu-En-Bugey,FABRE,Daniel,M,07/09/1961,74,Ancien cadre,18/05/2020,28/05/2020,FABRE Daniel
3,01,Ain,NaN,NaN,01005,Ambérieux-En-Dombes,FORNES,Christine,F,06/07/1962,21,Artisan,02/05/2021,07/05/2021,FORNES Christine
4,01,Ain,NaN,NaN,01006,Ambléon,BIONDA,Annie,F,28/11/1951,77,Ancien employé,18/05/2020,25/05/2020,BIONDA Annie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34869,NaN,NaN,988.0,Nouvelle-Calédonie,98829,Thio,TOURA,Jean-Patrick,M,12/05/1966,67,Ouvrier non qualifié de type industriel,28/06/2020,03/07/2020,TOURA Jean-Patrick
34870,NaN,NaN,988.0,Nouvelle-Calédonie,98830,Touho,POININE,Alphonse Boulet,M,16/04/1960,11,Agriculteur sur petite exploitation,18/05/2020,18/05/2020,POININE Alphonse Boulet
34871,NaN,NaN,988.0,Nouvelle-Calédonie,98831,Voh,BOATATE KOLEKOLE,Joel,M,19/10/1970,52,Employé civil et agent de service de la foncti...,28/06/2020,03/07/2020,BOATATE KOLEKOLE Joel
34872,NaN,NaN,988.0,Nouvelle-Calédonie,98832,Yaté,GOUETCHA,Victor,M,22/10/1960,38,Ingénieur et cadre technique d'entreprise,28/06/2020,03/07/2020,GOUETCHA Victor
34873,NaN,NaN,988.0,Nouvelle-Calédonie,98833,Kouaoua,HARI,Patrick,M,13/09/1975,21,Artisan,28/06/2020,24/01/2025,HARI Patrick