In [1]:
import os
import sys

In [2]:
sys.path.append(os.path.abspath('../..'))

In [3]:
from src.preprocessing import (load_and_clean_insee_2007_famille,
 load_and_clean_insee_2007_population,
 load_and_clean_insee_2007_population2,
 load_and_clean_insee_2007_nationalite,
 load_and_clean_insee_2007_nationalite2,
 load_and_clean_insee_2007_diplome,
 load_and_clean_insee_2007_logement,
 load_and_clean_insee_2007_menage,
 load_and_clean_insee_2007_immigration,
 load_and_clean_insee_2007_emploi)

In [4]:
df_famille_2007 = load_and_clean_insee_2007_famille(sheet="COM")

In [5]:
df_menage_2007 = load_and_clean_insee_2007_menage(sheet="COM")

In [6]:
df_diplome_2007 = load_and_clean_insee_2007_diplome(sheet="COM")

In [7]:
df_logement_2007 = load_and_clean_insee_2007_logement(sheet="COM")

In [8]:
df_population_2007 = load_and_clean_insee_2007_population(sheet="COM")
df_population_2007_2 = load_and_clean_insee_2007_population2(sheet="COM")

In [9]:
df_emploi_2007_1 = load_and_clean_insee_2007_emploi(sheet="1_COM")
df_emploi_2007_2 = load_and_clean_insee_2007_emploi(sheet="2_COM")

In [10]:
df_nationalite_2007 = load_and_clean_insee_2007_nationalite(sheet="COM")
df_nationalite_2007_2 = load_and_clean_insee_2007_nationalite2(sheet="COM")

In [11]:
df_immigration_2007 = load_and_clean_insee_2007_immigration(sheet="COM")

In [12]:
display(df_famille_2007.head())
display(df_menage_2007.head())
display(df_immigration_2007.head())
display(df_nationalite_2007.head())
display(df_nationalite_2007_2.head())
display(df_diplome_2007.head())
display(df_logement_2007.head())
display(df_population_2007.head())
display(df_population_2007_2.head())
display(df_emploi_2007_1.head())
display(df_emploi_2007_2.head())

,CODGEO,CS2_24,NBENFFR,Nombre
0,1001.0,Agriculteurs exploitants,Aucun enfant de moins de 25 ans,0
1,1001.0,Agriculteurs exploitants,1 enfant de moins de 25 ans,4
2,1001.0,Agriculteurs exploitants,2 enfants de moins de 25 ans,4
3,1001.0,Agriculteurs exploitants,3 enfants de moins de 25 ans,0
4,1001.0,Agriculteurs exploitants,4 enfants ou plus de moins de 25 ans,0

   CODGEO                    CS2_24        NPERC  Nombre
0  1001.0  Agriculteurs exploitants   1 personne       0
1  1001.0  Agriculteurs exploitants  2 personnes       0
2  1001.0  Agriculteurs exploitants  3 personnes       4
3  1001.0  Agriculteurs exploitants  4 personnes       4
4  1001.0  Agriculteurs exploitants  5 personnes       0

,CODGEO,SEXE,AGE4,TACTR,IMMI,Nombre
0,1001.0,Hommes,Moins de 15 ans,Actifs ayant un emploi,Immigrés,0
1,1001.0,Hommes,Moins de 15 ans,Actifs ayant un emploi,Non immigrés,0
2,1001.0,Hommes,Moins de 15 ans,Chômeurs,Immigrés,0
3,1001.0,Hommes,Moins de 15 ans,Chômeurs,Non immigrés,0
4,1001.0,Hommes,Moins de 15 ans,Retraités ou préretraités,Immigrés,0

   CODGEO    SEXE      INATC             AGE4  Nombre
0  1001.0  Hommes   Français  Moins de 15 ans     100
1  1001.0  Hommes   Français      15 à 24 ans      49
2  1001.0  Hommes   Français      25 à 54 ans     168
3  1001.0  Hommes   Français   55 ans ou plus      97
4  1001.0  Hommes  Etrangers  Moins de 15 ans       2

,CODGEO,SEXE,INATC,CS1_8,Nombre
0,1001.0,Hommes,Français,Agriculteurs exploitants,8
1,1001.0,Hommes,Français,"Artisans, commerçants, chefs entreprise",12
2,1001.0,Hommes,Français,Cadres et professions intellectuelles supérieures,28
3,1001.0,Hommes,Français,Professions intermédiaires,60
4,1001.0,Hommes,Français,Employés,8

,CODGEO,SEXE,AGEQ65,DIPL,Nombre
0,1001.0,Hommes,15 à 19 ans,Pas de scolarité,0
1,1001.0,Hommes,15 à 19 ans,Aucun diplôme mais scolarité jusqu'en école pr...,0
2,1001.0,Hommes,15 à 19 ans,Aucun diplôme mais scolarité au delà du collège,2
3,1001.0,Hommes,15 à 19 ans,Certificat d'études primaires,0
4,1001.0,Hommes,15 à 19 ans,"BEPC, brevet élémentaire, brevet des collèges",0

,CODGEO,TYPLR,CS1_8,STOCD,Nombre
0,1001.0,Maisons,Agriculteurs exploitants,Propriétaire,4
1,1001.0,Maisons,Agriculteurs exploitants,Locataire ou sous-locataire d'un logement loué...,4
2,1001.0,Maisons,Agriculteurs exploitants,Locataire ou sous-locataire d'un logement loué...,0
3,1001.0,Maisons,Agriculteurs exploitants,Locataire ou sous-locataire d'un logement loué...,0
4,1001.0,Maisons,Agriculteurs exploitants,Logé gratuitement,0

,CODGEO,SEXE,AGEQ65,TACTR,Nombre
0,1001.0,Hommes,15 à 19 ans,Actifs ayant un emploi,10
1,1001.0,Hommes,15 à 19 ans,Chômeurs,1
2,1001.0,Hommes,15 à 19 ans,Retraités ou préretraités,0
3,1001.0,Hommes,15 à 19 ans,"Elèves, étudiants, stagiaires non rémunérés",17
4,1001.0,Hommes,15 à 19 ans,Femmes ou hommes au foyer,0

   CODGEO    SEXE       AGEQ65 CS1_8  Nombre
0  1001.0  Hommes  15 à 19 ans  None      10
1  1001.0  Hommes  15 à 19 ans  None       1
2  1001.0  Hommes  15 à 19 ans  None       0
3  1001.0  Hommes  15 à 19 ans  None      17
4  1001.0  Hommes  15 à 19 ans  None       0

,CODGEO,SEXE,CS3_31,NA5,Nombre
0,1001.0,Hommes,Agriculteurs sur petite exploitation,"Agriculture, sylviculture et pêche",4
1,1001.0,Hommes,Agriculteurs sur petite exploitation,"Industrie manufacturière, industries extractiv...",0
2,1001.0,Hommes,Agriculteurs sur petite exploitation,Construction,0
3,1001.0,Hommes,Agriculteurs sur petite exploitation,"Commerce, transports et services divers",0
4,1001.0,Hommes,Agriculteurs sur petite exploitation,"Administration publique, enseignement, santé h...",0

,CODGEO,SEXE,CS3_31,NA5,Nombre
0,1001.0,None,Policiers et militaires,"Agriculture, sylviculture et pêche",0
1,1001.0,None,Policiers et militaires,"Industrie manufacturière, industries extractiv...",0
2,1001.0,None,Policiers et militaires,Construction,0
3,1001.0,None,Policiers et militaires,"Commerce, transports et services divers",0
4,1001.0,None,Policiers et militaires,"Administration publique, enseignement, santé h...",0

In [12]:
from src.preprocessing import (
    load_and_clean_insee_2013_famille,
    load_and_clean_insee_2013_menage,
    load_and_clean_insee_2013_diplome,
    load_and_clean_insee_2013_population,
    load_and_clean_insee_2013_population2,
    load_and_clean_insee_2013_nationalite,
    load_and_clean_insee_2013_nationalite2,
    load_and_clean_insee_2013_logement,
    load_and_clean_insee_2013_emploi,
    load_and_clean_insee_2013_immigration,
)

In [13]:
df_famille_2013_com      = load_and_clean_insee_2013_famille(sheet="COM")

In [14]:
df_menage_2013_com       = load_and_clean_insee_2013_menage(sheet="COM")

In [15]:
df_diplome_2013_com      = load_and_clean_insee_2013_diplome(sheet="COM")

In [16]:
df_population_2013_com   = load_and_clean_insee_2013_population(sheet="COM")
df_population2_2013_com  = load_and_clean_insee_2013_population2(sheet="COM")

In [17]:
df_nationalite_2013_com  = load_and_clean_insee_2013_nationalite(sheet="COM")
df_nationalite2_2013_com = load_and_clean_insee_2013_nationalite2(sheet="COM")

In [18]:
df_logement_2013_com     = load_and_clean_insee_2013_logement(sheet="COM")

In [ ]:
df_emploi_2013_com       = load_and_clean_insee_2013_emploi(sheet="COM")

In [19]:
df_immigration_2013  = load_and_clean_insee_2013_immigration(sheet="COM")

In [20]:
from src.preprocessing import (
    load_and_clean_insee_2019_famille,
    load_and_clean_insee_2019_menage,
    load_and_clean_insee_2019_diplome,
    load_and_clean_insee_2019_population,
    load_and_clean_insee_2019_population2,
    load_and_clean_insee_2019_nationalite,
    load_and_clean_insee_2019_nationalite2,
    load_and_clean_insee_2019_logement,
    load_and_clean_insee_2019_emploi,
    load_and_clean_insee_2019_immigration,
)

In [21]:
df_famille_2019_com      = load_and_clean_insee_2019_famille(sheet="COM")

In [ ]:
df_menage_2019_com       = load_and_clean_insee_2019_menage(sheet="COM")

In [ ]:
df_diplome_2019_com      = load_and_clean_insee_2019_diplome(sheet="COM")

In [ ]:
df_population_2019_com   = load_and_clean_insee_2019_population(sheet="COM")
df_population2_2019_com  = load_and_clean_insee_2019_population2(sheet="COM")

In [ ]:
df_nationalite_2019_com  = load_and_clean_insee_2019_nationalite(sheet="COM")
df_nationalite2_2019_com = load_and_clean_insee_2019_nationalite2(sheet="COM")

In [ ]:
df_logement_2019_com     = load_and_clean_insee_2019_logement(sheet="COM")

In [ ]:
df_emploi_2019_com       = load_and_clean_insee_2019_emploi(sheet="COM")

In [ ]:
df_immigration_2019_com = load_and_clean_insee_2019_immigration(sheet="COM")