In [1]:
import os
import sys

import pandas as pd

In [2]:
sys.path.append(os.path.abspath('../..'))

In [3]:
from src.preprocessing import load_and_clean_insee_2007_famille

In [4]:
df_famille_2007_arm = load_and_clean_insee_2007_famille(sheet="ARM")
display(df_famille_2007_arm.head(5))

,CODGEO,CS2_24,NBENFFR,Nombre
0,13201,Agriculteurs exploitants,Aucun enfant de moins de 25 ans,0
1,13201,Agriculteurs exploitants,1 enfant de moins de 25 ans,0
2,13201,Agriculteurs exploitants,2 enfants de moins de 25 ans,0
3,13201,Agriculteurs exploitants,3 enfants de moins de 25 ans,0
4,13201,Agriculteurs exploitants,4 enfants ou plus de moins de 25 ans,0

In [5]:
df_famille_2007_com = load_and_clean_insee_2007_famille(sheet="COM")
display(df_famille_2007_com.head(5))

,CODGEO,CS2_24,NBENFFR,Nombre
0,1001.0,Agriculteurs exploitants,Aucun enfant de moins de 25 ans,0
1,1001.0,Agriculteurs exploitants,1 enfant de moins de 25 ans,4
2,1001.0,Agriculteurs exploitants,2 enfants de moins de 25 ans,4
3,1001.0,Agriculteurs exploitants,3 enfants de moins de 25 ans,0
4,1001.0,Agriculteurs exploitants,4 enfants ou plus de moins de 25 ans,0

In [6]:
from src.preprocessing import load_and_clean_insee_2007_menage

In [7]:
df_menage_2007_arm = load_and_clean_insee_2007_menage(sheet="ARM")
display(df_menage_2007_arm.head(5))

   CODGEO                    CS2_24        NPERC  Nombre
0   13201  Agriculteurs exploitants   1 personne       1
1   13201  Agriculteurs exploitants  2 personnes       0
2   13201  Agriculteurs exploitants  3 personnes       0
3   13201  Agriculteurs exploitants  4 personnes       0
4   13201  Agriculteurs exploitants  5 personnes       0

In [8]:
df_menage_2007_arm = load_and_clean_insee_2007_menage(sheet="COM")
display(df_menage_2007_arm.head(5))

   CODGEO                    CS2_24        NPERC  Nombre
0  1001.0  Agriculteurs exploitants   1 personne       0
1  1001.0  Agriculteurs exploitants  2 personnes       0
2  1001.0  Agriculteurs exploitants  3 personnes       4
3  1001.0  Agriculteurs exploitants  4 personnes       4
4  1001.0  Agriculteurs exploitants  5 personnes       0

In [9]:
from src.preprocessing import load_and_clean_insee_2007_diplome

df_diplome_2007_arm = load_and_clean_insee_2007_diplome(sheet="ARM")
display(df_diplome_2007_arm.head(5))

sexe {'1': 'Hommes', '2': 'Femmes'} ageq65 {'015': '15 à 19 ans', '020': '20 à 24 ans', '025': '25 à 29 ans', '030': '30 à 34 ans', '035': '35 à 39 ans', '040': '40 à 44 ans', '045': '45 à 49 ans', '050': '50 à 54 ans', '055': '55 à 59 ans', '060': '60 à 64 ans', '065': '65 ans ou plus'} dipl {'01': 'Pas de scolarité', '02': "Aucun diplôme mais scolarité jusqu'en école primaire ou au collège", '03': 'Aucun diplôme mais scolarité au delà du collège', '11': "Certificat d'études primaires", '12': 'BEPC, brevet élémentaire, brevet des collèges', '13': "Certificat d'aptitudes professionnelles, brevet de compagnon", '14': "Brevet d'études professionnelles", '15': 'Baccalauréat général, brevet supérieur', '16': 'Bac technologique ou professionnel, brevet professionnel ou de technicien, BEC, BEI, BEH, capacité en droit', '17': "Diplôme universitaire de 1er cycle, BTS, DUT, diplôme des professions sociales ou de santé, d'infirmier(ère)", '18': 'Diplôme universitaire de 2ème ou 3ème cycle (y compris médecine, pharmacie, dentaire), diplôme'}

,CODGEO,SEXE,AGEQ65,DIPL,Nombre
0,13201,Hommes,15 à 19 ans,Pas de scolarité,0
1,13201,Hommes,15 à 19 ans,Aucun diplôme mais scolarité jusqu'en école pr...,34
2,13201,Hommes,15 à 19 ans,Aucun diplôme mais scolarité au delà du collège,36
3,13201,Hommes,15 à 19 ans,Certificat d'études primaires,4
4,13201,Hommes,15 à 19 ans,"BEPC, brevet élémentaire, brevet des collèges",26

In [10]:
df_diplome_2007_arm = load_and_clean_insee_2007_diplome(sheet="COM")
display(df_diplome_2007_arm.head(5))

sexe {'1': 'Hommes', '2': 'Femmes'} ageq65 {'015': '15 à 19 ans', '020': '20 à 24 ans', '025': '25 à 29 ans', '030': '30 à 34 ans', '035': '35 à 39 ans', '040': '40 à 44 ans', '045': '45 à 49 ans', '050': '50 à 54 ans', '055': '55 à 59 ans', '060': '60 à 64 ans', '065': '65 ans ou plus'} dipl {'01': 'Pas de scolarité', '02': "Aucun diplôme mais scolarité jusqu'en école primaire ou au collège", '03': 'Aucun diplôme mais scolarité au delà du collège', '11': "Certificat d'études primaires", '12': 'BEPC, brevet élémentaire, brevet des collèges', '13': "Certificat d'aptitudes professionnelles, brevet de compagnon", '14': "Brevet d'études professionnelles", '15': 'Baccalauréat général, brevet supérieur', '16': 'Bac technologique ou professionnel, brevet professionnel ou de technicien, BEC, BEI, BEH, capacité en droit', '17': "Diplôme universitaire de 1er cycle, BTS, DUT, diplôme des professions sociales ou de santé, d'infirmier(ère)", '18': 'Diplôme universitaire de 2ème ou 3ème cycle (y compris médecine, pharmacie, dentaire), diplôme'}

,CODGEO,SEXE,AGEQ65,DIPL,Nombre
0,1001.0,Hommes,15 à 19 ans,Pas de scolarité,0
1,1001.0,Hommes,15 à 19 ans,Aucun diplôme mais scolarité jusqu'en école pr...,0
2,1001.0,Hommes,15 à 19 ans,Aucun diplôme mais scolarité au delà du collège,2
3,1001.0,Hommes,15 à 19 ans,Certificat d'études primaires,0
4,1001.0,Hommes,15 à 19 ans,"BEPC, brevet élémentaire, brevet des collèges",0