In [1]:
import os
import sys

import pandas as pd

In [2]:
sys.path.append(os.path.abspath('../..'))

In [3]:
from src.preprocessing import load_and_clean_insee_2007_famille

In [4]:
df_famille_2007_arm = load_and_clean_insee_2007_famille(sheet="ARM")
display(df_famille_2007_arm.head(5))

,CODGEO,CS2_24,NBENFFR,Nombre
0,13201,Agriculteurs exploitants,Aucun enfant de moins de 25 ans,0
1,13201,Agriculteurs exploitants,1 enfant de moins de 25 ans,0
2,13201,Agriculteurs exploitants,2 enfants de moins de 25 ans,0
3,13201,Agriculteurs exploitants,3 enfants de moins de 25 ans,0
4,13201,Agriculteurs exploitants,4 enfants ou plus de moins de 25 ans,0

In [5]:
df_famille_2007_com = load_and_clean_insee_2007_famille(sheet="COM")
display(df_famille_2007_com.head(5))

,CODGEO,CS2_24,NBENFFR,Nombre
0,1001.0,Agriculteurs exploitants,Aucun enfant de moins de 25 ans,0
1,1001.0,Agriculteurs exploitants,1 enfant de moins de 25 ans,4
2,1001.0,Agriculteurs exploitants,2 enfants de moins de 25 ans,4
3,1001.0,Agriculteurs exploitants,3 enfants de moins de 25 ans,0
4,1001.0,Agriculteurs exploitants,4 enfants ou plus de moins de 25 ans,0

In [6]:
from src.preprocessing import load_and_clean_insee_2007_menage

In [7]:
df_menage_2007_arm = load_and_clean_insee_2007_menage(sheet="ARM")
display(df_menage_2007_arm.head(5))

   CODGEO                    CS2_24        NPERC  Nombre
0   13201  Agriculteurs exploitants   1 personne       1
1   13201  Agriculteurs exploitants  2 personnes       0
2   13201  Agriculteurs exploitants  3 personnes       0
3   13201  Agriculteurs exploitants  4 personnes       0
4   13201  Agriculteurs exploitants  5 personnes       0

In [ ]:
df_menage_2007_com = load_and_clean_insee_2007_menage(sheet="COM")
display(df_menage_2007_com.head(5))

   CODGEO                    CS2_24        NPERC  Nombre
0  1001.0  Agriculteurs exploitants   1 personne       0
1  1001.0  Agriculteurs exploitants  2 personnes       0
2  1001.0  Agriculteurs exploitants  3 personnes       4
3  1001.0  Agriculteurs exploitants  4 personnes       4
4  1001.0  Agriculteurs exploitants  5 personnes       0

In [9]:
from src.preprocessing import load_and_clean_insee_2007_diplome

df_diplome_2007_arm = load_and_clean_insee_2007_diplome(sheet="ARM")
display(df_diplome_2007_arm.head(5))

sexe {'1': 'Hommes', '2': 'Femmes'} ageq65 {'015': '15 à 19 ans', '020': '20 à 24 ans', '025': '25 à 29 ans', '030': '30 à 34 ans', '035': '35 à 39 ans', '040': '40 à 44 ans', '045': '45 à 49 ans', '050': '50 à 54 ans', '055': '55 à 59 ans', '060': '60 à 64 ans', '065': '65 ans ou plus'} dipl {'01': 'Pas de scolarité', '02': "Aucun diplôme mais scolarité jusqu'en école primaire ou au collège", '03': 'Aucun diplôme mais scolarité au delà du collège', '11': "Certificat d'études primaires", '12': 'BEPC, brevet élémentaire, brevet des collèges', '13': "Certificat d'aptitudes professionnelles, brevet de compagnon", '14': "Brevet d'études professionnelles", '15': 'Baccalauréat général, brevet supérieur', '16': 'Bac technologique ou professionnel, brevet professionnel ou de technicien, BEC, BEI, BEH, capacité en droit', '17': "Diplôme universitaire de 1er cycle, BTS, DUT, diplôme des professions sociales ou de santé, d'infirmier(ère)", '18': 'Diplôme universitaire de 2ème ou 3ème cycle (y compris médecine, pharmacie, dentaire), diplôme'}

,CODGEO,SEXE,AGEQ65,DIPL,Nombre
0,13201,Hommes,15 à 19 ans,Pas de scolarité,0
1,13201,Hommes,15 à 19 ans,Aucun diplôme mais scolarité jusqu'en école pr...,34
2,13201,Hommes,15 à 19 ans,Aucun diplôme mais scolarité au delà du collège,36
3,13201,Hommes,15 à 19 ans,Certificat d'études primaires,4
4,13201,Hommes,15 à 19 ans,"BEPC, brevet élémentaire, brevet des collèges",26

In [ ]:
df_diplome_2007_com = load_and_clean_insee_2007_diplome(sheet="COM")
display(df_diplome_2007_com.head(5))

sexe {'1': 'Hommes', '2': 'Femmes'} ageq65 {'015': '15 à 19 ans', '020': '20 à 24 ans', '025': '25 à 29 ans', '030': '30 à 34 ans', '035': '35 à 39 ans', '040': '40 à 44 ans', '045': '45 à 49 ans', '050': '50 à 54 ans', '055': '55 à 59 ans', '060': '60 à 64 ans', '065': '65 ans ou plus'} dipl {'01': 'Pas de scolarité', '02': "Aucun diplôme mais scolarité jusqu'en école primaire ou au collège", '03': 'Aucun diplôme mais scolarité au delà du collège', '11': "Certificat d'études primaires", '12': 'BEPC, brevet élémentaire, brevet des collèges', '13': "Certificat d'aptitudes professionnelles, brevet de compagnon", '14': "Brevet d'études professionnelles", '15': 'Baccalauréat général, brevet supérieur', '16': 'Bac technologique ou professionnel, brevet professionnel ou de technicien, BEC, BEI, BEH, capacité en droit', '17': "Diplôme universitaire de 1er cycle, BTS, DUT, diplôme des professions sociales ou de santé, d'infirmier(ère)", '18': 'Diplôme universitaire de 2ème ou 3ème cycle (y compris médecine, pharmacie, dentaire), diplôme'}

,CODGEO,SEXE,AGEQ65,DIPL,Nombre
0,1001.0,Hommes,15 à 19 ans,Pas de scolarité,0
1,1001.0,Hommes,15 à 19 ans,Aucun diplôme mais scolarité jusqu'en école pr...,0
2,1001.0,Hommes,15 à 19 ans,Aucun diplôme mais scolarité au delà du collège,2
3,1001.0,Hommes,15 à 19 ans,Certificat d'études primaires,0
4,1001.0,Hommes,15 à 19 ans,"BEPC, brevet élémentaire, brevet des collèges",0

In [ ]:
from src.preprocessing import load_and_clean_insee_2007_population

df_nationalite_2007_arm = load_and_clean_insee_2007_population(sheet="ARM")
display(df_nationalite_2007_arm.head(5))

,CODGEO,SEXE,AGEQ65,TACTR,Nombre
0,13201,Hommes,15 à 19 ans,Actifs ayant un emploi,130
1,13201,Hommes,15 à 19 ans,Chômeurs,50
2,13201,Hommes,15 à 19 ans,Retraités ou préretraités,0
3,13201,Hommes,15 à 19 ans,"Elèves, étudiants, stagiaires non rémunérés",1152
4,13201,Hommes,15 à 19 ans,Femmes ou hommes au foyer,3

In [ ]:


df_nationalite_2007_com = load_and_clean_insee_2007_population(sheet="COM")
display(df_nationalite_2007_com.head(5))

,CODGEO,SEXE,AGEQ65,TACTR,Nombre
0,1001.0,Hommes,15 à 19 ans,Actifs ayant un emploi,10
1,1001.0,Hommes,15 à 19 ans,Chômeurs,1
2,1001.0,Hommes,15 à 19 ans,Retraités ou préretraités,0
3,1001.0,Hommes,15 à 19 ans,"Elèves, étudiants, stagiaires non rémunérés",17
4,1001.0,Hommes,15 à 19 ans,Femmes ou hommes au foyer,0

In [5]:
from src.preprocessing import load_and_clean_insee_2007_population2

df_nationalite_2007_arm = load_and_clean_insee_2007_population(sheet="ARM")
display(df_nationalite_2007_arm.head(5))

,CODGEO,SEXE,AGEQ65,TACTR,Nombre
0,13201,Hommes,15 à 19 ans,Actifs ayant un emploi,130
1,13201,Hommes,15 à 19 ans,Chômeurs,50
2,13201,Hommes,15 à 19 ans,Retraités ou préretraités,0
3,13201,Hommes,15 à 19 ans,"Elèves, étudiants, stagiaires non rémunérés",1152
4,13201,Hommes,15 à 19 ans,Femmes ou hommes au foyer,3

In [ ]:


df_population_2007_com = load_and_clean_insee_2007_population(sheet="COM")
display(df_population_2007_com.head(5))

,CODGEO,SEXE,AGEQ65,TACTR,Nombre
0,1001.0,Hommes,15 à 19 ans,Actifs ayant un emploi,10
1,1001.0,Hommes,15 à 19 ans,Chômeurs,1
2,1001.0,Hommes,15 à 19 ans,Retraités ou préretraités,0
3,1001.0,Hommes,15 à 19 ans,"Elèves, étudiants, stagiaires non rémunérés",17
4,1001.0,Hommes,15 à 19 ans,Femmes ou hommes au foyer,0

In [ ]:
from src.preprocessing import load_and_clean_insee_2007_immigration

df_immigration_2007_arm = load_and_clean_insee_2007_immigration(sheet="ARM")
display(df_immigration_2007_arm.head(5))

,CODGEO,SEXE,AGE4,TACTR,IMMI,Nombre
0,13201,Hommes,Moins de 15 ans,Actifs ayant un emploi,Immigrés,0
1,13201,Hommes,Moins de 15 ans,Actifs ayant un emploi,Non immigrés,2
2,13201,Hommes,Moins de 15 ans,Chômeurs,Immigrés,0
3,13201,Hommes,Moins de 15 ans,Chômeurs,Non immigrés,0
4,13201,Hommes,Moins de 15 ans,Retraités ou préretraités,Immigrés,0

In [3]:
from src.preprocessing import load_and_clean_insee_2007_nationalite

df_nationalite_2007_arm = load_and_clean_insee_2007_nationalite(sheet="ARM")
display(df_nationalite_2007_arm.head(5))

   CODGEO    SEXE      INATC             AGE4  Nombre
0   13201  Hommes   Français  Moins de 15 ans    3023
1   13201  Hommes   Français      15 à 24 ans    2724
2   13201  Hommes   Français      25 à 54 ans    6679
3   13201  Hommes   Français   55 ans ou plus    3022
4   13201  Hommes  Etrangers  Moins de 15 ans     728

In [ ]:
from src.preprocessing import load_and_clean_insee_2007_nationalite2

df_nationalite2_2007_arm = load_and_clean_insee_2007_nationalite2(sheet="ARM")
display(df_nationalite2_2007_arm.head(5))

,CODGEO,SEXE,INATC,CS1_8,Nombre
0,13201,Hommes,Français,Agriculteurs exploitants,1
1,13201,Hommes,Français,"Artisans, commerçants, chefs entreprise",536
2,13201,Hommes,Français,Cadres et professions intellectuelles supérieures,1866
3,13201,Hommes,Français,Professions intermédiaires,1773
4,13201,Hommes,Français,Employés,1531

In [ ]:
from src.preprocessing import load_and_clean_insee_2007_nationalite2

df_nationalite2_2007_arm = load_and_clean_insee_2007_nationalite2(sheet="ARM")
display(df_nationalite2_2007_arm.head(5))

,CODGEO,SEXE,INATC,CS1_8,Nombre
0,13201,Hommes,Français,Agriculteurs exploitants,1
1,13201,Hommes,Français,"Artisans, commerçants, chefs entreprise",536
2,13201,Hommes,Français,Cadres et professions intellectuelles supérieures,1866
3,13201,Hommes,Français,Professions intermédiaires,1773
4,13201,Hommes,Français,Employés,1531

In [ ]:
from src.preprocessing import load_and_clean_insee_2007_logement

df_logement_2007_arm = load_and_clean_insee_2007_logement(sheet="ARM")
display(df_logement_2007_arm.head(5))

,CODGEO,TYPLR,CS1_8,STOCD,Nombre
0,13201,Maisons,Agriculteurs exploitants,Propriétaire,0
1,13201,Maisons,Agriculteurs exploitants,Locataire ou sous-locataire d'un logement loué...,0
2,13201,Maisons,Agriculteurs exploitants,Locataire ou sous-locataire d'un logement loué...,0
3,13201,Maisons,Agriculteurs exploitants,Locataire ou sous-locataire d'un logement loué...,0
4,13201,Maisons,Agriculteurs exploitants,Logé gratuitement,0

In [ ]:

df_logement_2007_com = load_and_clean_insee_2007_logement(sheet="COM")
display(df_logement_2007_com.head(5))

,CODGEO,TYPLR,CS1_8,STOCD,Nombre
0,1001.0,Maisons,Agriculteurs exploitants,Propriétaire,4
1,1001.0,Maisons,Agriculteurs exploitants,Locataire ou sous-locataire d'un logement loué...,4
2,1001.0,Maisons,Agriculteurs exploitants,Locataire ou sous-locataire d'un logement loué...,0
3,1001.0,Maisons,Agriculteurs exploitants,Locataire ou sous-locataire d'un logement loué...,0
4,1001.0,Maisons,Agriculteurs exploitants,Logé gratuitement,0

In [4]:
from src.preprocessing import load_and_clean_insee_2007_emploi

df_emploi_2007_1arm = load_and_clean_insee_2007_emploi(sheet="1_ARM")
display(df_emploi_2007_1arm.head(5))

,CODGEO,SEXE,CS3_31,NA5,Nombre
0,13201,Hommes,Agriculteurs sur petite exploitation,"Agriculture, sylviculture et pêche",0
1,13201,Hommes,Agriculteurs sur petite exploitation,"Industrie manufacturière, industries extractiv...",0
2,13201,Hommes,Agriculteurs sur petite exploitation,Construction,0
3,13201,Hommes,Agriculteurs sur petite exploitation,"Commerce, transports et services divers",0
4,13201,Hommes,Agriculteurs sur petite exploitation,"Administration publique, enseignement, santé h...",0

In [8]:
df_emploi_2007_2arm = load_and_clean_insee_2007_emploi(sheet="2_ARM")
display(df_emploi_2007_2arm.head(10))

,CODGEO,SEXE,CS3_31,NA5,Nombre
0,13201,None,Policiers et militaires,"Agriculture, sylviculture et pêche",0
1,13201,None,Policiers et militaires,"Industrie manufacturière, industries extractiv...",0
2,13201,None,Policiers et militaires,Construction,0
3,13201,None,Policiers et militaires,"Commerce, transports et services divers",9
4,13201,None,Policiers et militaires,"Administration publique, enseignement, santé h...",68
5,13201,None,Employés administratifs d'entreprise,"Agriculture, sylviculture et pêche",0
6,13201,None,Employés administratifs d'entreprise,"Industrie manufacturière, industries extractiv...",38
7,13201,None,Employés administratifs d'entreprise,Construction,41
8,13201,None,Employés administratifs d'entreprise,"Commerce, transports et services divers",991
9,13201,None,Employés administratifs d'entreprise,"Administration publique, enseignement, santé h...",300

In [6]:
df_emploi_2007_2com = load_and_clean_insee_2007_emploi(sheet="1_COM")
display(df_emploi_2007_2com.head(5))

,CODGEO,SEXE,CS3_31,NA5,Nombre
0,1001.0,Hommes,Agriculteurs sur petite exploitation,"Agriculture, sylviculture et pêche",4
1,1001.0,Hommes,Agriculteurs sur petite exploitation,"Industrie manufacturière, industries extractiv...",0
2,1001.0,Hommes,Agriculteurs sur petite exploitation,Construction,0
3,1001.0,Hommes,Agriculteurs sur petite exploitation,"Commerce, transports et services divers",0
4,1001.0,Hommes,Agriculteurs sur petite exploitation,"Administration publique, enseignement, santé h...",0

In [7]:
df_emploi_2007_2com = load_and_clean_insee_2007_emploi(sheet="2_COM")
display(df_emploi_2007_2com.head(5))

,CODGEO,SEXE,CS3_31,NA5,Nombre
0,1001.0,None,Policiers et militaires,"Agriculture, sylviculture et pêche",0
1,1001.0,None,Policiers et militaires,"Industrie manufacturière, industries extractiv...",0
2,1001.0,None,Policiers et militaires,Construction,0
3,1001.0,None,Policiers et militaires,"Commerce, transports et services divers",0
4,1001.0,None,Policiers et militaires,"Administration publique, enseignement, santé h...",0

In [3]:
from src.preprocessing import (
    load_and_clean_insee_2013_famille,
    load_and_clean_insee_2013_menage,
    load_and_clean_insee_2013_diplome,
    load_and_clean_insee_2013_population,
    load_and_clean_insee_2013_population2,
    load_and_clean_insee_2013_nationalite,
    load_and_clean_insee_2013_nationalite2,
    load_and_clean_insee_2013_logement,
    load_and_clean_insee_2013_emploi,
    load_and_clean_insee_2013_immigration,
)

df_famille_2013_com      = load_and_clean_insee_2013_famille(sheet="COM")
df_menage_2013_com       = load_and_clean_insee_2013_menage(sheet="COM")
df_diplome_2013_com      = load_and_clean_insee_2013_diplome(sheet="COM")
df_population_2013_com   = load_and_clean_insee_2013_population(sheet="COM")
df_population2_2013_com  = load_and_clean_insee_2013_population2(sheet="COM")
df_nationalite_2013_com  = load_and_clean_insee_2013_nationalite(sheet="COM")
df_nationalite2_2013_com = load_and_clean_insee_2013_nationalite2(sheet="COM")
df_logement_2013_com     = load_and_clean_insee_2013_logement(sheet="COM")
df_emploi_2013_com       = load_and_clean_insee_2013_emploi(sheet="COM")
df_immigration_2013_com  = load_and_clean_insee_2013_immigration(sheet="COM")

display(df_diplome_2013_com.head(5))

,CODGEO,LIBGEO,AGEQ65,DIPL,SEXE,Nombre
0,01001,L'Abergement-Clémenciat,15 à 19 ans,"Aucun diplôme ou au plus BEPC, brevet des coll...",Hommes,0
1,01002,L'Abergement-de-Varey,15 à 19 ans,"Aucun diplôme ou au plus BEPC, brevet des coll...",Hommes,0
2,01004,Ambérieu-en-Bugey,15 à 19 ans,"Aucun diplôme ou au plus BEPC, brevet des coll...",Hommes,51
3,01005,Ambérieux-en-Dombes,15 à 19 ans,"Aucun diplôme ou au plus BEPC, brevet des coll...",Hommes,3
4,01006,Ambléon,15 à 19 ans,"Aucun diplôme ou au plus BEPC, brevet des coll...",Hommes,1

In [4]:
from src.preprocessing import (
    load_and_clean_insee_2013_famille,
    load_and_clean_insee_2013_menage,
    load_and_clean_insee_2013_diplome,
    load_and_clean_insee_2013_population,
    load_and_clean_insee_2013_population2,
    load_and_clean_insee_2013_nationalite,
    load_and_clean_insee_2013_nationalite2,
    load_and_clean_insee_2013_logement,
    load_and_clean_insee_2013_emploi,
    load_and_clean_insee_2013_immigration,
)

df_famille_2013_arm      = load_and_clean_insee_2013_famille(sheet="ARM")
df_menage_2013_arm       = load_and_clean_insee_2013_menage(sheet="ARM")
df_diplome_2013_arm      = load_and_clean_insee_2013_diplome(sheet="ARM")
df_population_2013_arm   = load_and_clean_insee_2013_population(sheet="ARM")
df_population2_2013_arm  = load_and_clean_insee_2013_population2(sheet="ARM")
df_nationalite_2013_arm  = load_and_clean_insee_2013_nationalite(sheet="ARM")
df_nationalite2_2013_arm = load_and_clean_insee_2013_nationalite2(sheet="ARM")
df_logement_2013_arm     = load_and_clean_insee_2013_logement(sheet="ARM")
df_emploi_2013_arm       = load_and_clean_insee_2013_emploi(sheet="ARM")
df_immigration_2013_arm  = load_and_clean_insee_2013_immigration(sheet="ARM")

display(df_diplome_2013_arm.head(5))
display(df_famille_2013_arm.head(5))
display(df_menage_2013_arm.head(5))
display(df_immigration_2013_arm.head(5))
display(df_emploi_2013_arm.head(5))
display(df_logement_2013_arm.head(5))
display(df_nationalite_2013_arm.head(5))
display(df_nationalite2_2013_arm.head(5))
display(df_population_2013_arm.head(5))
display(df_population2_2013_arm.head(5))

,CODGEO,LIBGEO,AGEQ65,DIPL,SEXE,Nombre
0,13201,Marseille 1er Arrondissement,15 à 19 ans,"Aucun diplôme ou au plus BEPC, brevet des coll...",Hommes,77
1,13202,Marseille 2e Arrondissement,15 à 19 ans,"Aucun diplôme ou au plus BEPC, brevet des coll...",Hommes,72
2,13203,Marseille 3e Arrondissement,15 à 19 ans,"Aucun diplôme ou au plus BEPC, brevet des coll...",Hommes,160
3,13204,Marseille 4e Arrondissement,15 à 19 ans,"Aucun diplôme ou au plus BEPC, brevet des coll...",Hommes,75
4,13205,Marseille 5e Arrondissement,15 à 19 ans,"Aucun diplôme ou au plus BEPC, brevet des coll...",Hommes,88

,CODGEO,LIBGEO,CS2_24,NBENFFR,Nombre
0,13201,Marseille 1er Arrondissement,Agriculteurs exploitants,Aucun enfant de moins de 25 ans,0
1,13202,Marseille 2e Arrondissement,Agriculteurs exploitants,Aucun enfant de moins de 25 ans,0
2,13203,Marseille 3e Arrondissement,Agriculteurs exploitants,Aucun enfant de moins de 25 ans,0
3,13204,Marseille 4e Arrondissement,Agriculteurs exploitants,Aucun enfant de moins de 25 ans,2
4,13205,Marseille 5e Arrondissement,Agriculteurs exploitants,Aucun enfant de moins de 25 ans,3

,CODGEO,LIBGEO,NPERC,CS2_24,Nombre
0,13201,Marseille 1er Arrondissement,1 personne,Agriculteurs exploitants,0
1,13202,Marseille 2e Arrondissement,1 personne,Agriculteurs exploitants,0
2,13203,Marseille 3e Arrondissement,1 personne,Agriculteurs exploitants,0
3,13204,Marseille 4e Arrondissement,1 personne,Agriculteurs exploitants,3
4,13205,Marseille 5e Arrondissement,1 personne,Agriculteurs exploitants,0

,CODGEO,LIBGEO,SEXE,AGE4_A,IMMI,TACTR,Nombre
0,13201,Marseille 1er Arrondissement,Hommes,15 à 24 ans,Immigrés,Actifs ayant un emploi,122
1,13202,Marseille 2e Arrondissement,Hommes,15 à 24 ans,Immigrés,Actifs ayant un emploi,56
2,13203,Marseille 3e Arrondissement,Hommes,15 à 24 ans,Immigrés,Actifs ayant un emploi,149
3,13204,Marseille 4e Arrondissement,Hommes,15 à 24 ans,Immigrés,Actifs ayant un emploi,76
4,13205,Marseille 5e Arrondissement,Hommes,15 à 24 ans,Immigrés,Actifs ayant un emploi,43

,CODGEO,LIBGEO,CS3_29,NA5,SEXE,Nombre
0,13201,Marseille 1er Arrondissement,Agriculteurs exploitants,"Agriculture, sylviculture et pêche",Hommes,3
1,13202,Marseille 2e Arrondissement,Agriculteurs exploitants,"Agriculture, sylviculture et pêche",Hommes,5
2,13203,Marseille 3e Arrondissement,Agriculteurs exploitants,"Agriculture, sylviculture et pêche",Hommes,0
3,13204,Marseille 4e Arrondissement,Agriculteurs exploitants,"Agriculture, sylviculture et pêche",Hommes,7
4,13205,Marseille 5e Arrondissement,Agriculteurs exploitants,"Agriculture, sylviculture et pêche",Hommes,3

,CODGEO,LIBGEO,CS1_8,STOCD,TYPLR,Nombre
0,13201,Marseille 1er Arrondissement,Agriculteurs exploitants,Propriétaire,Maisons,0
1,13202,Marseille 2e Arrondissement,Agriculteurs exploitants,Propriétaire,Maisons,0
2,13203,Marseille 3e Arrondissement,Agriculteurs exploitants,Propriétaire,Maisons,0
3,13204,Marseille 4e Arrondissement,Agriculteurs exploitants,Propriétaire,Maisons,0
4,13205,Marseille 5e Arrondissement,Agriculteurs exploitants,Propriétaire,Maisons,0

,CODGEO,LIBGEO,AGE4,INATC,SEXE,Nombre
0,13201,Marseille 1er Arrondissement,Moins de 15 ans,Français,Hommes,2677
1,13202,Marseille 2e Arrondissement,Moins de 15 ans,Français,Hommes,1814
2,13203,Marseille 3e Arrondissement,Moins de 15 ans,Français,Hommes,4259
3,13204,Marseille 4e Arrondissement,Moins de 15 ans,Français,Hommes,3839
4,13205,Marseille 5e Arrondissement,Moins de 15 ans,Français,Hommes,3289

,CODGEO,LIBGEO,CS1_8,INATC,SEXE,Nombre
0,13201,Marseille 1er Arrondissement,Agriculteurs exploitants,Français,Hommes,0
1,13202,Marseille 2e Arrondissement,Agriculteurs exploitants,Français,Hommes,4
2,13203,Marseille 3e Arrondissement,Agriculteurs exploitants,Français,Hommes,3
3,13204,Marseille 4e Arrondissement,Agriculteurs exploitants,Français,Hommes,10
4,13205,Marseille 5e Arrondissement,Agriculteurs exploitants,Français,Hommes,12

,CODGEO,LIBGEO,SEXE,AGEQ65,TACTR,Nombre
0,13201,Marseille 1er Arrondissement,Hommes,15 à 19 ans,Actifs ayant un emploi,90
1,13202,Marseille 2e Arrondissement,Hommes,15 à 19 ans,Actifs ayant un emploi,77
2,13203,Marseille 3e Arrondissement,Hommes,15 à 19 ans,Actifs ayant un emploi,111
3,13204,Marseille 4e Arrondissement,Hommes,15 à 19 ans,Actifs ayant un emploi,141
4,13205,Marseille 5e Arrondissement,Hommes,15 à 19 ans,Actifs ayant un emploi,120

,CODGEO,LIBGEO,CS1_8,AGEQ65,SEXE,Nombre
0,13201,Marseille 1er Arrondissement,Agriculteurs exploitants,15 à 19 ans,Hommes,0
1,13202,Marseille 2e Arrondissement,Agriculteurs exploitants,15 à 19 ans,Hommes,0
2,13203,Marseille 3e Arrondissement,Agriculteurs exploitants,15 à 19 ans,Hommes,0
3,13204,Marseille 4e Arrondissement,Agriculteurs exploitants,15 à 19 ans,Hommes,0
4,13205,Marseille 5e Arrondissement,Agriculteurs exploitants,15 à 19 ans,Hommes,0

In [5]:
from src.preprocessing import (
    load_and_clean_insee_2019_famille,
    load_and_clean_insee_2019_menage,
    load_and_clean_insee_2019_diplome,
    load_and_clean_insee_2019_population,
    load_and_clean_insee_2019_population2,
    load_and_clean_insee_2019_nationalite,
    load_and_clean_insee_2019_nationalite2,
    load_and_clean_insee_2019_logement,
    load_and_clean_insee_2019_emploi,
    load_and_clean_insee_2019_immigration,
)

df_famille_2019_com      = load_and_clean_insee_2019_famille(sheet="COM")
df_menage_2019_com       = load_and_clean_insee_2019_menage(sheet="COM")
df_diplome_2019_com      = load_and_clean_insee_2019_diplome(sheet="COM")
df_population_2019_com   = load_and_clean_insee_2019_population(sheet="COM")
df_population2_2019_com  = load_and_clean_insee_2019_population2(sheet="COM")
df_nationalite_2019_com  = load_and_clean_insee_2019_nationalite(sheet="COM")
df_nationalite2_2019_com = load_and_clean_insee_2019_nationalite2(sheet="COM")
df_logement_2019_com     = load_and_clean_insee_2019_logement(sheet="COM")
df_emploi_2019_com       = load_and_clean_insee_2019_emploi(sheet="COM")
# df_immigration_2019_com = load_and_clean_insee_2019_immigration(sheet="COM")
#   ^ pas de feuille COM pour ce fichier en 2019 (seulement C.O.M. = outre-mer)

display(df_diplome_2019_com.head(5))

,CODGEO,LIBGEO,AGEQ65,DIPL,SEXE,Nombre
0,01001,L'Abergement-Clémenciat,15 à 19 ans,Aucun diplôme ou certificat d'études primaires,Hommes,1
1,01002,L'Abergement-de-Varey,15 à 19 ans,Aucun diplôme ou certificat d'études primaires,Hommes,0
2,01004,Ambérieu-en-Bugey,15 à 19 ans,Aucun diplôme ou certificat d'études primaires,Hommes,32
3,01005,Ambérieux-en-Dombes,15 à 19 ans,Aucun diplôme ou certificat d'études primaires,Hommes,1
4,01006,Ambléon,15 à 19 ans,Aucun diplôme ou certificat d'études primaires,Hommes,0