In [1]:
import os
import sys

import pandas as pd

In [2]:
sys.path.append(os.path.abspath('../..'))

In [3]:
from src.preprocessing import load_and_clean_insee_2007_famille

In [4]:
df_famille_2007_arm = load_and_clean_insee_2007_famille(sheet="ARM")
display(df_famille_2007_arm.head(5))

,CODGEO,CS2_24,NBENFFR,Nombre
0,13201,Agriculteurs exploitants,Aucun enfant de moins de 25 ans,0
1,13201,Agriculteurs exploitants,1 enfant de moins de 25 ans,0
2,13201,Agriculteurs exploitants,2 enfants de moins de 25 ans,0
3,13201,Agriculteurs exploitants,3 enfants de moins de 25 ans,0
4,13201,Agriculteurs exploitants,4 enfants ou plus de moins de 25 ans,0

In [5]:
df_famille_2007_com = load_and_clean_insee_2007_famille(sheet="COM")
display(df_famille_2007_com.head(5))

,CODGEO,CS2_24,NBENFFR,Nombre
0,1001.0,Agriculteurs exploitants,Aucun enfant de moins de 25 ans,0
1,1001.0,Agriculteurs exploitants,1 enfant de moins de 25 ans,4
2,1001.0,Agriculteurs exploitants,2 enfants de moins de 25 ans,4
3,1001.0,Agriculteurs exploitants,3 enfants de moins de 25 ans,0
4,1001.0,Agriculteurs exploitants,4 enfants ou plus de moins de 25 ans,0

In [6]:
from src.preprocessing import load_and_clean_insee_2007_menage

In [7]:
df_menage_2007_arm = load_and_clean_insee_2007_menage(sheet="ARM")
display(df_menage_2007_arm.head(5))

   CODGEO                    CS2_24        NPERC  Nombre
0   13201  Agriculteurs exploitants   1 personne       1
1   13201  Agriculteurs exploitants  2 personnes       0
2   13201  Agriculteurs exploitants  3 personnes       0
3   13201  Agriculteurs exploitants  4 personnes       0
4   13201  Agriculteurs exploitants  5 personnes       0

In [8]:
df_menage_2007_arm = load_and_clean_insee_2007_menage(sheet="COM")
display(df_menage_2007_arm.head(5))

   CODGEO                    CS2_24        NPERC  Nombre
0  1001.0  Agriculteurs exploitants   1 personne       0
1  1001.0  Agriculteurs exploitants  2 personnes       0
2  1001.0  Agriculteurs exploitants  3 personnes       4
3  1001.0  Agriculteurs exploitants  4 personnes       4
4  1001.0  Agriculteurs exploitants  5 personnes       0

In [9]:
from src.preprocessing import load_and_clean_insee_2007_diplome

df_diplome_2007_arm = load_and_clean_insee_2007_diplome(sheet="ARM")
display(df_diplome_2007_arm.head(5))

sexe {'1': 'Hommes', '2': 'Femmes'} ageq65 {'015': '15 à 19 ans', '020': '20 à 24 ans', '025': '25 à 29 ans', '030': '30 à 34 ans', '035': '35 à 39 ans', '040': '40 à 44 ans', '045': '45 à 49 ans', '050': '50 à 54 ans', '055': '55 à 59 ans', '060': '60 à 64 ans', '065': '65 ans ou plus'} dipl {'01': 'Pas de scolarité', '02': "Aucun diplôme mais scolarité jusqu'en école primaire ou au collège", '03': 'Aucun diplôme mais scolarité au delà du collège', '11': "Certificat d'études primaires", '12': 'BEPC, brevet élémentaire, brevet des collèges', '13': "Certificat d'aptitudes professionnelles, brevet de compagnon", '14': "Brevet d'études professionnelles", '15': 'Baccalauréat général, brevet supérieur', '16': 'Bac technologique ou professionnel, brevet professionnel ou de technicien, BEC, BEI, BEH, capacité en droit', '17': "Diplôme universitaire de 1er cycle, BTS, DUT, diplôme des professions sociales ou de santé, d'infirmier(ère)", '18': 'Diplôme universitaire de 2ème ou 3ème cycle (y compris médecine, pharmacie, dentaire), diplôme'}

,CODGEO,SEXE,AGEQ65,DIPL,Nombre
0,13201,Hommes,15 à 19 ans,Pas de scolarité,0
1,13201,Hommes,15 à 19 ans,Aucun diplôme mais scolarité jusqu'en école pr...,34
2,13201,Hommes,15 à 19 ans,Aucun diplôme mais scolarité au delà du collège,36
3,13201,Hommes,15 à 19 ans,Certificat d'études primaires,4
4,13201,Hommes,15 à 19 ans,"BEPC, brevet élémentaire, brevet des collèges",26

In [10]:
df_diplome_2007_arm = load_and_clean_insee_2007_diplome(sheet="COM")
display(df_diplome_2007_arm.head(5))

sexe {'1': 'Hommes', '2': 'Femmes'} ageq65 {'015': '15 à 19 ans', '020': '20 à 24 ans', '025': '25 à 29 ans', '030': '30 à 34 ans', '035': '35 à 39 ans', '040': '40 à 44 ans', '045': '45 à 49 ans', '050': '50 à 54 ans', '055': '55 à 59 ans', '060': '60 à 64 ans', '065': '65 ans ou plus'} dipl {'01': 'Pas de scolarité', '02': "Aucun diplôme mais scolarité jusqu'en école primaire ou au collège", '03': 'Aucun diplôme mais scolarité au delà du collège', '11': "Certificat d'études primaires", '12': 'BEPC, brevet élémentaire, brevet des collèges', '13': "Certificat d'aptitudes professionnelles, brevet de compagnon", '14': "Brevet d'études professionnelles", '15': 'Baccalauréat général, brevet supérieur', '16': 'Bac technologique ou professionnel, brevet professionnel ou de technicien, BEC, BEI, BEH, capacité en droit', '17': "Diplôme universitaire de 1er cycle, BTS, DUT, diplôme des professions sociales ou de santé, d'infirmier(ère)", '18': 'Diplôme universitaire de 2ème ou 3ème cycle (y compris médecine, pharmacie, dentaire), diplôme'}

,CODGEO,SEXE,AGEQ65,DIPL,Nombre
0,1001.0,Hommes,15 à 19 ans,Pas de scolarité,0
1,1001.0,Hommes,15 à 19 ans,Aucun diplôme mais scolarité jusqu'en école pr...,0
2,1001.0,Hommes,15 à 19 ans,Aucun diplôme mais scolarité au delà du collège,2
3,1001.0,Hommes,15 à 19 ans,Certificat d'études primaires,0
4,1001.0,Hommes,15 à 19 ans,"BEPC, brevet élémentaire, brevet des collèges",0

In [3]:
from src.preprocessing import load_and_clean_insee_2007_population

df_nationalite_2007_arm = load_and_clean_insee_2007_population(sheet="ARM")
display(df_nationalite_2007_arm.head(5))

,CODGEO,SEXE,AGEQ65,TACTR,Nombre
0,13201,Hommes,15 à 19 ans,Actifs ayant un emploi,130
1,13201,Hommes,15 à 19 ans,Chômeurs,50
2,13201,Hommes,15 à 19 ans,Retraités ou préretraités,0
3,13201,Hommes,15 à 19 ans,"Elèves, étudiants, stagiaires non rémunérés",1152
4,13201,Hommes,15 à 19 ans,Femmes ou hommes au foyer,3

In [4]:


df_nationalite_2007_arm = load_and_clean_insee_2007_population(sheet="COM")
display(df_nationalite_2007_arm.head(5))

,CODGEO,SEXE,AGEQ65,TACTR,Nombre
0,1001.0,Hommes,15 à 19 ans,Actifs ayant un emploi,10
1,1001.0,Hommes,15 à 19 ans,Chômeurs,1
2,1001.0,Hommes,15 à 19 ans,Retraités ou préretraités,0
3,1001.0,Hommes,15 à 19 ans,"Elèves, étudiants, stagiaires non rémunérés",17
4,1001.0,Hommes,15 à 19 ans,Femmes ou hommes au foyer,0

In [5]:
from src.preprocessing import load_and_clean_insee_2007_population2

df_nationalite_2007_arm = load_and_clean_insee_2007_population(sheet="ARM")
display(df_nationalite_2007_arm.head(5))

,CODGEO,SEXE,AGEQ65,TACTR,Nombre
0,13201,Hommes,15 à 19 ans,Actifs ayant un emploi,130
1,13201,Hommes,15 à 19 ans,Chômeurs,50
2,13201,Hommes,15 à 19 ans,Retraités ou préretraités,0
3,13201,Hommes,15 à 19 ans,"Elèves, étudiants, stagiaires non rémunérés",1152
4,13201,Hommes,15 à 19 ans,Femmes ou hommes au foyer,3

In [ ]:


df_population_2007_arm = load_and_clean_insee_2007_population(sheet="COM")
display(df_population_2007_arm.head(5))

,CODGEO,SEXE,AGEQ65,TACTR,Nombre
0,1001.0,Hommes,15 à 19 ans,Actifs ayant un emploi,10
1,1001.0,Hommes,15 à 19 ans,Chômeurs,1
2,1001.0,Hommes,15 à 19 ans,Retraités ou préretraités,0
3,1001.0,Hommes,15 à 19 ans,"Elèves, étudiants, stagiaires non rémunérés",17
4,1001.0,Hommes,15 à 19 ans,Femmes ou hommes au foyer,0

In [ ]:
from src.preprocessing import load_and_clean_insee_2007_immigration

df_immigration_2007_arm = load_and_clean_insee_2007_immigration(sheet="ARM")
display(df_immigration_2007_arm.head(5))

,CODGEO,SEXE,AGE4,TACTR,IMMI,Nombre
0,13201,Hommes,Moins de 15 ans,Actifs ayant un emploi,Immigrés,0
1,13201,Hommes,Moins de 15 ans,Actifs ayant un emploi,Non immigrés,2
2,13201,Hommes,Moins de 15 ans,Chômeurs,Immigrés,0
3,13201,Hommes,Moins de 15 ans,Chômeurs,Non immigrés,0
4,13201,Hommes,Moins de 15 ans,Retraités ou préretraités,Immigrés,0

In [3]:
from src.preprocessing import load_and_clean_insee_2007_nationalite

df_nationalite_2007_arm = load_and_clean_insee_2007_nationalite(sheet="ARM")
display(df_nationalite_2007_arm.head(5))

   CODGEO    SEXE      INATC             AGE4  Nombre
0   13201  Hommes   Français  Moins de 15 ans    3023
1   13201  Hommes   Français      15 à 24 ans    2724
2   13201  Hommes   Français      25 à 54 ans    6679
3   13201  Hommes   Français   55 ans ou plus    3022
4   13201  Hommes  Etrangers  Moins de 15 ans     728

In [ ]:
from src.preprocessing import load_and_clean_insee_2007_nationalite2

df_nationalite2_2007_arm = load_and_clean_insee_2007_nationalite2(sheet="ARM")
display(df_nationalite2_2007_arm.head(5))

,CODGEO,SEXE,INATC,CS1_8,Nombre
0,13201,Hommes,Français,Agriculteurs exploitants,1
1,13201,Hommes,Français,"Artisans, commerçants, chefs entreprise",536
2,13201,Hommes,Français,Cadres et professions intellectuelles supérieures,1866
3,13201,Hommes,Français,Professions intermédiaires,1773
4,13201,Hommes,Français,Employés,1531

In [ ]:
from src.preprocessing import load_and_clean_insee_2007_nationalite2

df_nationalite2_2007_arm = load_and_clean_insee_2007_nationalite2(sheet="ARM")
display(df_nationalite2_2007_arm.head(5))

,CODGEO,SEXE,INATC,CS1_8,Nombre
0,13201,Hommes,Français,Agriculteurs exploitants,1
1,13201,Hommes,Français,"Artisans, commerçants, chefs entreprise",536
2,13201,Hommes,Français,Cadres et professions intellectuelles supérieures,1866
3,13201,Hommes,Français,Professions intermédiaires,1773
4,13201,Hommes,Français,Employés,1531

In [ ]:
from src.preprocessing import load_and_clean_insee_2007_logement

df_logement_2007_arm = load_and_clean_insee_2007_logement(sheet="ARM")
display(df_logement_2007_arm.head(5))

,CODGEO,TYPLR,CS1_8,STOCD,Nombre
0,13201,Maisons,Agriculteurs exploitants,Propriétaire,0
1,13201,Maisons,Agriculteurs exploitants,Locataire ou sous-locataire d'un logement loué...,0
2,13201,Maisons,Agriculteurs exploitants,Locataire ou sous-locataire d'un logement loué...,0
3,13201,Maisons,Agriculteurs exploitants,Locataire ou sous-locataire d'un logement loué...,0
4,13201,Maisons,Agriculteurs exploitants,Logé gratuitement,0

In [ ]:

df_logement_2007_arm = load_and_clean_insee_2007_logement(sheet="COM")
display(df_logement_2007_arm.head(5))

,CODGEO,TYPLR,CS1_8,STOCD,Nombre
0,1001.0,Maisons,Agriculteurs exploitants,Propriétaire,4
1,1001.0,Maisons,Agriculteurs exploitants,Locataire ou sous-locataire d'un logement loué...,4
2,1001.0,Maisons,Agriculteurs exploitants,Locataire ou sous-locataire d'un logement loué...,0
3,1001.0,Maisons,Agriculteurs exploitants,Locataire ou sous-locataire d'un logement loué...,0
4,1001.0,Maisons,Agriculteurs exploitants,Logé gratuitement,0

In [3]:
from src.preprocessing import load_and_clean_insee_2007_emploi

df_emploi_2007_arm = load_and_clean_insee_2007_emploi(sheet="1_ARM")
display(df_emploi_2007_arm.head(5))

,CODGEO,SEXE,CS3_31,NA5,Nombre
0,13201,Hommes,Agriculteurs sur petite exploitation,"Agriculture, sylviculture et pêche",0
1,13201,Hommes,Agriculteurs sur petite exploitation,"Industrie manufacturière, industries extractiv...",0
2,13201,Hommes,Agriculteurs sur petite exploitation,Construction,0
3,13201,Hommes,Agriculteurs sur petite exploitation,"Commerce, transports et services divers",0
4,13201,Hommes,Agriculteurs sur petite exploitation,"Administration publique, enseignement, santé h...",0

In [4]:
df_emploi_2007_arm = load_and_clean_insee_2007_emploi(sheet="2_ARM")
display(df_emploi_2007_arm.head(5))

,CODGEO,SEXE,CS3_31,NA5,Nombre
0,13201,None,Policiers et militaires,"Agriculture, sylviculture et pêche",0
1,13201,None,Policiers et militaires,"Industrie manufacturière, industries extractiv...",0
2,13201,None,Policiers et militaires,Construction,0
3,13201,None,Policiers et militaires,"Commerce, transports et services divers",9
4,13201,None,Policiers et militaires,"Administration publique, enseignement, santé h...",68

In [5]:
df_emploi_2007_arm = load_and_clean_insee_2007_emploi(sheet="2_COM")
display(df_emploi_2007_arm.head(5))

,CODGEO,SEXE,CS3_31,NA5,Nombre
0,1001.0,None,Policiers et militaires,"Agriculture, sylviculture et pêche",0
1,1001.0,None,Policiers et militaires,"Industrie manufacturière, industries extractiv...",0
2,1001.0,None,Policiers et militaires,Construction,0
3,1001.0,None,Policiers et militaires,"Commerce, transports et services divers",0
4,1001.0,None,Policiers et militaires,"Administration publique, enseignement, santé h...",0

In [6]:
df_emploi_2007_arm = load_and_clean_insee_2007_emploi(sheet="2_COM")
display(df_emploi_2007_arm.head(5))

,CODGEO,SEXE,CS3_31,NA5,Nombre
0,1001.0,None,Policiers et militaires,"Agriculture, sylviculture et pêche",0
1,1001.0,None,Policiers et militaires,"Industrie manufacturière, industries extractiv...",0
2,1001.0,None,Policiers et militaires,Construction,0
3,1001.0,None,Policiers et militaires,"Commerce, transports et services divers",0
4,1001.0,None,Policiers et militaires,"Administration publique, enseignement, santé h...",0