In [1]:
import os
import sys

import pandas as pd

In [2]:
sys.path.append(os.path.abspath('../..'))

In [3]:
from src.preprocessing import load_and_clean_insee_2007_famille

In [4]:
df_famille_2007_arm = load_and_clean_insee_2007_famille(sheet="ARM")
display(df_famille_2007_arm.head(5))

,CODGEO,CS2_24,NBENFFR,Nombre
0,13201,Agriculteurs exploitants,Aucun enfant de moins de 25 ans,0
1,13201,Agriculteurs exploitants,1 enfant de moins de 25 ans,0
2,13201,Agriculteurs exploitants,2 enfants de moins de 25 ans,0
3,13201,Agriculteurs exploitants,3 enfants de moins de 25 ans,0
4,13201,Agriculteurs exploitants,4 enfants ou plus de moins de 25 ans,0

In [5]:
df_famille_2007_com = load_and_clean_insee_2007_famille(sheet="COM")
display(df_famille_2007_com.head(5))

,CODGEO,CS2_24,NBENFFR,Nombre
0,1001.0,Agriculteurs exploitants,Aucun enfant de moins de 25 ans,0
1,1001.0,Agriculteurs exploitants,1 enfant de moins de 25 ans,4
2,1001.0,Agriculteurs exploitants,2 enfants de moins de 25 ans,4
3,1001.0,Agriculteurs exploitants,3 enfants de moins de 25 ans,0
4,1001.0,Agriculteurs exploitants,4 enfants ou plus de moins de 25 ans,0