In [259]:
import sys
import os

In [260]:
sys.path.append(os.path.abspath('../..'))

In [261]:
from src.preprocessing import load_and_clean_ville_stats_histo

In [284]:
df_data,df_metadata = load_and_clean_ville_stats_histo()

C:\Users\julie\OneDrive\Documents\info\B3\election\src\preprocessing.py:22: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv(RAW_DATA_FILES['stat_ville_histo'], sep=';')

In [263]:
df_data

,FREQ,GEO,GEO_OBJECT,OCS,RP_MEASURE,TIME_PERIOD,OBS_VALUE
0,A,88068,COM,_T,BRTH,2006,43.00000
1,A,85139,COM,_T,BRTH,1975,51.00000
2,A,85034,COM,_T,BRTH,1982,217.00000
3,A,88064,COM,_T,BRTH,2022,5.00000
4,A,85112,COM,_T,BRTH,2016,125.00000
...,...,...,...,...,...,...,...
2945320,A,95678,COM,DW_SEC_DW_OCC,DWELLINGS,1990,23.00000
2945321,A,97132,COM,DW_SEC_DW_OCC,DWELLINGS,2011,181.68207
2945322,A,97101,COM,DW_MAIN,DWELLINGS,2011,24582.47432
2945323,A,97120,COM,DW_MAIN,DWELLINGS,2011,7919.24715
2945324,A,95607,COM,DW_SEC_DW_OCC,DWELLINGS,1982,77.00000

In [264]:
df_data.shape

(2945325, 7)

In [265]:
df_metadata.head()

,COD_VAR,LIB_VAR,COD_MOD,LIB_MOD
0,FREQ,Fréquence,A,Annuel
1,OCS,Catégorie de logement,DW_MAIN,Résidences principales
2,OCS,Catégorie de logement,DW_SEC_DW_OCC,Résidences secondaires et logements occasionnels
3,OCS,Catégorie de logement,DW_VAC,Logements vacants
4,OCS,Catégorie de logement,_T,Total

In [266]:
df_data['FREQ'].unique()

array(['A'], dtype=object)

In [285]:
df_data.drop(columns=['FREQ'], inplace=True)

In [268]:
df_metadata['COD_VAR'].unique()

array(['FREQ', 'OCS', 'RP_MEASURE', 'TIME_PERIOD', 'GEO'], dtype=object)

In [292]:
df_metadata_geo = df_metadata[df_metadata['COD_VAR'].isin(['GEO'])]
df_metadata_geo

,COD_VAR,LIB_VAR,COD_MOD,LIB_MOD
20,GEO,Géographie,200000172,Communauté de communes Faucigny-Glières
21,GEO,Géographie,200000438,Communauté de communes du Pays de Pontchâteau ...
22,GEO,Géographie,200000545,Communauté de communes des Portes de Romilly-s...
23,GEO,Géographie,200000628,Communauté de communes Rhône Lez Provence
24,GEO,Géographie,200000800,Communauté de communes Cœur de Sologne
...,...,...,...,...
41785,GEO,Géographie,13202,Marseille 2e Arrondissement
41786,GEO,Géographie,13203,Marseille 3e Arrondissement
41787,GEO,Géographie,13204,Marseille 4e Arrondissement
41788,GEO,Géographie,13205,Marseille 5e Arrondissement
41789,GEO,Géographie,13206,Marseille 6e Arrondissement

In [294]:
doublon_cod = df_metadata_geo[df_metadata_geo['COD_MOD'].duplicated(keep=False)]
doublon_cod

      COD_VAR     LIB_VAR COD_MOD                      LIB_MOD
1270      GEO  Géographie   67463                        Seltz
1271      GEO  Géographie   67474           Soultz-sous-Forêts
1272      GEO  Géographie   67482                   Strasbourg
1273      GEO  Géographie   67495                Truchtersheim
1274      GEO  Géographie   67507                        Villé
...       ...         ...     ...                          ...
41785     GEO  Géographie   13202  Marseille 2e Arrondissement
41786     GEO  Géographie   13203  Marseille 3e Arrondissement
41787     GEO  Géographie   13204  Marseille 4e Arrondissement
41788     GEO  Géographie   13205  Marseille 5e Arrondissement
41789     GEO  Géographie   13206  Marseille 6e Arrondissement

[7618 rows x 4 columns]

In [295]:
df_metadata_geo.drop_duplicates(keep='first', inplace=True)

C:\Users\julie\AppData\Local\Temp\ipykernel_25580\694721802.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_metadata_geo.drop_duplicates(keep='first', inplace=True)

In [296]:
doublon_cod = df_metadata_geo[df_metadata_geo['COD_MOD'].duplicated(keep=False)]
doublon_cod

      COD_VAR     LIB_VAR COD_MOD                      LIB_MOD
1284      GEO  Géographie   68112                   Guebwiller
1287      GEO  Géographie   68201         Masevaux-Niederbruck
1308      GEO  Géographie   69201      Sainte-Foy-l'Argentière
1401      GEO  Géographie   74105                     Douvaine
1413      GEO  Géographie   83104                        Rians
...       ...         ...     ...                          ...
41785     GEO  Géographie   13202  Marseille 2e Arrondissement
41786     GEO  Géographie   13203  Marseille 3e Arrondissement
41787     GEO  Géographie   13204  Marseille 4e Arrondissement
41788     GEO  Géographie   13205  Marseille 5e Arrondissement
41789     GEO  Géographie   13206  Marseille 6e Arrondissement

[4326 rows x 4 columns]

In [287]:
df_data = df_data.merge(df_metadata_geo[['COD_MOD', 'LIB_MOD']], left_on="GEO", right_on="COD_MOD", how="left")
df_data.shape

(3368925, 8)

In [297]:
df_data[df_data['GEO'] == "75101"]

,GEO,GEO_OBJECT,OCS,RP_MEASURE,TIME_PERIOD,OBS_VALUE,COD_MOD,LIB_MOD
232236,75101,ARM,DW_VAC,DWELLINGS,1982,1643.00000,75101,Paris 1er Arrondissement
232359,75101,ARM,DW_MAIN,DWELLINGS,2022,9316.30799,75101,Paris 1er Arrondissement
232936,75101,ARM,_T,BRTH,1982,1681.00000,75101,Paris 1er Arrondissement
233743,75101,ARM,_T,POP,1982,18509.00000,75101,Paris 1er Arrondissement
234272,75101,ARM,DW_MAIN,DWELLINGS_POPSIZE,1975,22639.00000,75101,Paris 1er Arrondissement
...,...,...,...,...,...,...,...,...
333302,75101,ARM,DW_MAIN,DWELLINGS,1990,10174.00000,75101,Paris 1er Arrondissement
333532,75101,ARM,DW_VAC,DWELLINGS,2022,1547.35026,75101,Paris 1er Arrondissement
333843,75101,ARM,DW_MAIN,DWELLINGS,1999,9890.00000,75101,Paris 1er Arrondissement
334786,75101,ARM,_T,BRTH,1968,3163.00000,75101,Paris 1er Arrondissement
335288,75101,ARM,_T,DEATH,2011,515.00000,75101,Paris 1er Arrondissement

In [271]:
df_data.drop(columns=['COD_MOD', "GEO"], inplace=True)

In [272]:
df_data =df_data.merge(df_metadata[['COD_MOD', 'LIB_MOD']], left_on="OCS", right_on="COD_MOD", how="left")
df_data.shape

(3368925, 8)

In [273]:
df_data.drop(columns=['COD_MOD', "OCS"], inplace=True)

In [274]:
df_data =df_data.merge(df_metadata[['COD_MOD', 'LIB_MOD']], left_on="RP_MEASURE", right_on="COD_MOD", how="left")
df_data.shape

(3368925, 8)

In [275]:
df_data.drop(columns=['COD_MOD', 'RP_MEASURE'], inplace=True)

In [276]:
df_data

,GEO_OBJECT,TIME_PERIOD,OBS_VALUE,LIB_MOD_x,LIB_MOD_y,LIB_MOD
0,COM,2006,43.00000,La Bourgonce,Total,Nombre de naissances
1,COM,1975,51.00000,Sainte-Florence,Total,Nombre de naissances
2,COM,1975,51.00000,Le Mazeau,Total,Nombre de naissances
3,COM,1982,217.00000,Bournezeau,Total,Nombre de naissances
4,COM,2022,5.00000,Bois-de-Champ,Total,Nombre de naissances
...,...,...,...,...,...,...
3368920,COM,1990,23.00000,NaN,Résidences secondaires et logements occasionnels,Logements
3368921,COM,2011,181.68207,NaN,Résidences secondaires et logements occasionnels,Logements
3368922,COM,2011,24582.47432,NaN,Résidences principales,Logements
3368923,COM,2011,7919.24715,NaN,Résidences principales,Logements
3368924,COM,1982,77.00000,NaN,Résidences secondaires et logements occasionnels,Logements

In [277]:
df_data['GEO_OBJECT'].unique()

array(['COM', 'EPCI', 'BV2022', 'ARM', 'AAV2020', 'ZE2020', 'UU2020',
       'ARR', 'FRANCE', 'DEP', 'REG'], dtype=object)

In [278]:
df_data.rename(columns={
    'OBS_VALUE': 'VALEUR',
    'LIB_MOD': 'MESURE',
    'LIB_MOD_x': 'GEO',
    'LIB_MOD_y': 'OCS'
}, inplace=True)

In [279]:
df_data.shape

(3368925, 6)

In [280]:
df_data_drop = df_data.drop_duplicates(subset=['GEO_OBJECT','GEO', 'OCS', 'MESURE', 'TIME_PERIOD'], keep='first')

In [281]:
df_data_drop.shape

(1664196, 6)

In [282]:
mask = df_data.duplicated(subset=['GEO_OBJECT', 'GEO', 'OCS', 'MESURE', 'TIME_PERIOD', 'VALEUR'], keep=False)
df_doublons = df_data[mask].sort_values(['GEO_OBJECT', 'GEO', 'OCS', 'MESURE', 'TIME_PERIOD', 'VALEUR'])
df_doublons

,GEO_OBJECT,TIME_PERIOD,VALEUR,GEO,OCS,MESURE
189268,BV2022,1968,809.0,Abbeville,Logements vacants,Logements
189269,BV2022,1968,809.0,Abbeville,Logements vacants,Logements
207840,BV2022,1975,1054.0,Abbeville,Logements vacants,Logements
207841,BV2022,1975,1054.0,Abbeville,Logements vacants,Logements
254089,BV2022,1982,1335.0,Abbeville,Logements vacants,Logements
...,...,...,...,...,...,...
988298,UU2020,2016,6735.0,Vallet,Total,Population
1049408,UU2020,2022,7037.0,Vallet,Total,Population
1049410,UU2020,2022,7037.0,Vallet,Total,Population
1073603,UU2020,2022,3628.0,Vallet,Total,Superficie
1073605,UU2020,2022,3628.0,Vallet,Total,Superficie

In [283]:
df_data_grouped = df_data.groupby(['GEO_OBJECT', 'GEO', 'OCS', 'MESURE', 'TIME_PERIOD'], as_index=False).agg({
    'VALEUR': 'sum'
})